_BASE_: "../Base-RCNN-FPN.yaml"
DATALOADER:
  COPY_PASTE: True
  COPY_PASTE_RATE: 1.0
  VISUALIZE_COPY_PASTE: False
  COPY_PASTE_RANDOM_NUM: False
  COPY_PASTE_MIN_RATIO: 0.5
  COPY_PASTE_MAX_RATIO: 1.0
  NUM_WORKERS: 2
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: 'output/cad_on_votecut/model_final.pth'
  MASK_ON: True
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "SyncBN"
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_HEADS:
    NAME: CustomCascadeROIHeads
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.0
    POSITIVE_FRACTION: 0.25
    USE_DROPLOSS: True
    DROPLOSS_IOU_THRESH: 0.01
    USE_SOFT_TARGETS: True
  ROI_MASK_HEAD:
    NAME: CustomMaskRCNNConvUpsampleHead
DATASETS:
  TRAIN: ("coco_train_17_self_training",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.05
  STEPS: (7400,)
  MAX_ITER: 14800
  GAMMA: 0.02
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (240, 320, 480, 640, 672, 704, 736, 768, 800, 1024)
  MAX_SIZE_TRAIN: 1333
  MASK_FORMAT: "bitmask"
  FORMAT: "RGB"
TEST:
  PRECISE_BN:
    ENABLED: True
    NUM_ITER: 200
  DETECTIONS_PER_IMAGE: 100
OUTPUT_DIR: "output/soft_self_train/"
